<a href="https://colab.research.google.com/github/Dev-YJ/test/blob/master/%EB%8B%A8%EC%96%B4%EC%9D%98_%ED%91%9C%ED%98%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#인코딩 대상 단어들을 담은 리스트
word_ls = ['원숭이', '바나나', '사과']

In [0]:
from collections import defaultdict
import numpy as np

def one_hot_encode(word_ls):
  #고유 단어와 인덱스를 매칭시켜주는 사전 생성
  word2idx_dic = defaultdict(lambda:len(word2idx_dic))
  
  # {단어 : 인덱스} 사전 구축
  for word in word_ls:
    word2idx_dic[word]
    
  n_unique_words = len(word2idx_dic) #고유한 단어의 갯수
  one_hot_vectors = np.zeros((len(word_ls), n_unique_words))
    
  for i, word in enumerate(word_ls):
    index = word2idx_dic[word] # 해당 단어의 고유 인덱스
    one_hot_vectors[i, index] += 1 # 해당 단어의 고유 인덱스에만 1을 
      
      
  return one_hot_vectors

In [0]:
one_hot_vectors = one_hot_encode(word_ls)
one_hot_vectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
# sklearn을 활용한 one-hot encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# 예제 데이터 배열
values = array(word_ls)
print(values)

# 문자열에 숫자를 붙임
label_enc = LabelEncoder()
int_enc = label_enc.fit_transform(values)
print(int_enc)

# binary encode
onehot_enc = OneHotEncoder(sparse=False) # sparse는 표기법. true로 하면 출력 형태가 달라짐
int_enc = int_enc.reshape(len(int_enc), 1) # n:1 matrix로 변환
onehot_enc = onehot_enc.fit_transform(int_enc)
print(onehot_enc)

# one-ot encoding의 첫번째 배열의 값을 역으로 산출
inverted = label_enc.inverse_transform([argmax(onehot_enc[0, :])])
print(inverted)

['원숭이' '바나나' '사과']
[2 0 1]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
['원숭이']


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [0]:
#밀집벡터
word_embedding_dic ={
    '사과' : [1.0,0.5],
    '바나나' :[0.9,1.2],
    '원숭이' : [0.5,1.5]
}

In [0]:
import numpy as np
def euclidean_dist(x,y):
  x = np.array(x)
  y = np.array(y)
  return np.sqrt(np.sum(x-y)**2)

#사과와 바나나의 코사인 유사도
euclidean_dist(word_embedding_dic['사과'], word_embedding_dic['바나나'])

0.6

In [0]:
s1 = '대부분 원숭이는 바나나를 좋아합니다.'
s2 = '코주부 원숭이는 바나나를 싫어합니다.'

#토큰화를 수행합니다.
token_s1 = s1.split()
token_s2 = s2.split()

union = set(token_s1).union(set(token_s2))
print(union)

intersection = set(token_s1).intersection(set(token_s2))
print(intersection)

print(len(intersection)/len(union)) #2를 6으로 나눔

{'코주부', '대부분', '싫어합니다.', '원숭이는', '바나나를', '좋아합니다.'}
{'원숭이는', '바나나를'}
0.3333333333333333


In [0]:
intersection = set(token_s1).intersection(set(token_s2))
print(intersection)

{'원숭이는', '바나나를'}


In [0]:
print(len(intersection)/len(union)) #2를 6으로 나눔

0.3333333333333333


In [0]:
def cosine_similarity(x,y):
  #x와 y, 두 벡터의 코사인 유사도를 계산하는 함수
  nominator = np.dot(x,y) #분자
  denomninator = np.linalg.norm(x)*np.linalg.norm(y) #분모
  return nominator/denomninator
    

In [0]:
#사과와 바나나의 코사인 유사도
print(cosine_similarity(word_embedding_dic['사과'], word_embedding_dic['바나나']))
print(euclidean_dist(word_embedding_dic['사과'], word_embedding_dic['바나나']))


0.8944271909999159
0.6


In [0]:
#바나나와 원숭이의 코사인 유사도
print(cosine_similarity(word_embedding_dic['바나나'], word_embedding_dic['원숭이']))
print(euclidean_dist(word_embedding_dic['바나나'], word_embedding_dic['원숭이']))


In [0]:
# 구글 드라이브에서 csv 파일을 읽어오기 위해 gauth 인증을 합니다.
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

     |████████████████████████████████| 993kB 355kB/s 


In [0]:
url_it ='https://drive.google.com/open?id=10EwI9yEZIIYDu2eDUiNIb1l5v8CfXb0_'
id_it = url_it.split('=')[1]
print(id_it)

url_culture ='https://drive.google.com/open?id=1dIqTcT4RP5LrY0M27PrMruNygBhlO_t9'
id_culture = url_culture.split('=')[1]
print(id_culture)

10EwI9yEZIIYDu2eDUiNIb1l5v8CfXb0_
1dIqTcT4RP5LrY0M27PrMruNygBhlO_t9


In [0]:
%ls

adc.json  sample_data/


In [0]:
# it관련 기사를 판다스를 통해 읽어온다.
downloaded = drive.CreateFile({'id':id_it}) 
downloaded.GetContentFile('2_word_embedding_it.csv')  

# 문화관련 기사를 판다스를 통해 읽어온다.
downloaded = drive.CreateFile({'id':id_culture}) 
downloaded.GetContentFile('2_word_embedding_culture.csv')  

In [0]:
%ls

2_word_embedding_culture.csv  2_word_embedding_it.csv  adc.json  sample_data/


In [0]:
import pandas as pd
it_df = pd.read_csv('2_word_embedding_it.csv').dropna() # 디폴트로 NaN이 1개라도 포함되면 해당 행이 삭제
culture_df = pd.read_csv('2_word_embedding_culture.csv').dropna()

In [0]:
#1헤더에 있는 값(기사, 토큰값)을 가져온다.

it_token_ls = list(it_df.loc[:,'1'])
culture_token_ls = list(culture_df.loc[:,'1'])
total_token_ls = it_token_ls + culture_token_ls


In [0]:
#토큰들이 ','로 분리되어 있는 상태

total_token_ls[0]

'배,정회,신임,과학기술,일자리,진흥,원장,아시아,경제,이민,우,배,정회,전,국립,중앙,과학,관,전시,연구,단장,과학기술,일자리,진흥,제,원장,취임,과학기술,정보,통신,같은,인사,발표,임기,날,동안,배,신임,원장,행정,고등고시,공직,입문,교육,과학기술,부,융합,기술,과장,중앙대,경영,경제,초빙교수,과기,정통부,연구,성과,활용,정책,과장,연구,성과,혁신,기획,과장,과학기술,정책,수립,정부,연구개발,연구,기술,이전,사업,두루,경험,보유,평가,배,신임,원장,날,환담,회,새로운,임무,조직,신속히,성하고,직원,역량,강화하겠다,며,실험실,유망,기술,전,문,기업,연결하며,기술,이전,효과,지원,신,기술,창업,통한,미래,일자리,많이,창,고,이민,우,네이버,홈,아시아,경제,뉴스,확인,재미,신기,과학,꿀,잼,인,기,만화,경제,눈,세계,창,아시아,경제,전,재'

In [0]:
#토큰들을 ','로 분리

total_token_ls = [tokens.split(',') for tokens in total_token_ls]

In [0]:
total_token_ls[0][:10]

['배', '정회', '신임', '과학기술', '일자리', '진흥', '원장', '아시아', '경제', '이민']

In [0]:
!pip install paramiko
from gensim.models import Word2Vec

     |████████████████████████████████| 194kB 4.9MB/s 
     |████████████████████████████████| 61kB 21.4MB/s 
     |████████████████████████████████| 2.3MB 41.8MB/s 
     |████████████████████████████████| 768kB 40.3MB/s 
     |████████████████████████████████| 102kB 28.6MB/s 


In [0]:
#띄어쓰기 단위로 토큰화

In [0]:
sentence_ls = [
    '오늘 동물원에서 코끼리를 봤어',
    '오늘 동물원에서 원숭이에게 사과를 줬어'
]

In [0]:
sentence_ls = [sentence.split() for sentence in sentence_ls]

In [0]:
sentence_ls

[['오늘', '동물원에서', '코끼리를', '봤어'], ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [0]:
from collections import defaultdict

token_dict = defaultdict(lambda : len(token_dict))

for sentence in sentence_ls:
  for token in sentence:
    token_dict[token]

In [0]:
token_dict

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '봤어': 3,
             '사과를': 5,
             '오늘': 0,
             '원숭이에게': 4,
             '줬어': 6,
             '코끼리를': 2})

In [0]:
index_token_ls = sorted((value, key) for key, value in token_dict.items())
index_token_ls

[(0, '오늘'),
 (1, '동물원에서'),
 (2, '코끼리를'),
 (3, '봤어'),
 (4, '원숭이에게'),
 (5, '사과를'),
 (6, '줬어')]

In [0]:
token_in_order = [tup[1] for tup in index_token_ls]
token_in_order

['오늘', '동물원에서', '코끼리를', '봤어', '원숭이에게', '사과를', '줬어']

In [0]:
import pandas as pd
import numpy as np

n_words = len(token_dict) # 전체 고유 토큰의 수
n_sentence = len(sentence_ls) # 전체 문장의 수

BOW = pd.DataFrame(
  np.zeros((n_sentence, n_words)),
  columns = token_in_order,
  index = ['문장1', '문장2'],
  dtype = int,
)

In [0]:
for i, sentence in enumerate(sentence_ls):
  for token in sentence:
    
    token_location = token_dict[token] # 해당 토큰의 위치(column)
    BOW.iloc[i, token_location] += 1

In [0]:
BOW

오늘  동물원에서  코끼리를  봤어  원숭이에게  사과를  줬어
문장1   2      2     2   2      0    0   0
문장2   2      2     0   0      2    2   2

In [0]:
sentence_ls2 = [
    '나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
    '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해'
]

In [0]:
sentence_ls2 = [sentence.split() for sentence in sentence_ls2]

In [0]:
sentence_ls2

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [0]:
from collections import defaultdict

token_dict2 = defaultdict(lambda : len(token_dict2))

for sentence in sentence_ls2:
  for token in sentence:
    token_dict2[token]

In [0]:
token_dict2


defaultdict(<function __main__.<lambda>>,
            {'나는': 0,
             '싫어해': 6,
             '양념': 1,
             '좋아해': 3,
             '치킨을': 2,
             '하지만': 4,
             '후라이드': 5})

In [0]:
index_token_ls2 = sorted((value, key) for key, value in token_dict2.items())
index_token_ls2

[(0, '나는'),
 (1, '양념'),
 (2, '치킨을'),
 (3, '좋아해'),
 (4, '하지만'),
 (5, '후라이드'),
 (6, '싫어해')]

In [0]:
token_in_order2 = [tup[1] for tup in index_token_ls2]
token_in_order2

['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']

In [0]:
import pandas as pd
import numpy as np

n_words = len(token_dict2) # 전체 고유 토큰의 수
n_sentence = len(sentence_ls2) # 전체 문장의 수

BOW2 = pd.DataFrame(
  np.zeros((n_sentence, n_words)),
  columns = token_in_order2,
  index = ['문장1', '문장2'],
  dtype = int,
)

In [0]:
for i, sentence in enumerate(sentence_ls2):
  for token in sentence:
    
    token_location2 = token_dict2[token] # 해당 토큰의 위치(column)
    BOW2.iloc[i, token_location2] += 1

In [0]:
BOW2

나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
문장1   1   1    2    1    1     1    1
문장2   1   1    2    1    1     1    1

5) TF-IDF 계산

In [0]:
d1 = "The cat sat on my face. I hate a cat."
d2 = "The dog sat on my bed. I love a dog."

In [0]:
bowA = d1.split()
bowB = d2.split()


In [0]:
wordSet = set(bowA).union(set(bowB))

In [0]:
wordSet

{'I',
 'The',
 'a',
 'bed.',
 'cat',
 'cat.',
 'dog',
 'dog.',
 'face.',
 'hate',
 'love',
 'my',
 'on',
 'sat'}

In [0]:
wordDictA = dict.fromkeys(wordSet,0)
wordDictB = dict.fromkeys(wordSet,0)

In [0]:
wordDictA

{'I': 0,
 'The': 0,
 'a': 0,
 'bed.': 0,
 'cat': 0,
 'cat.': 0,
 'dog': 0,
 'dog.': 0,
 'face.': 0,
 'hate': 0,
 'love': 0,
 'my': 0,
 'on': 0,
 'sat': 0}

In [0]:
for word in bowA:
    wordDictA[word]+=1
for word in bowB:
    wordDictB[word]+=1

In [0]:
import pandas as pd
pd.DataFrame([wordDictA,wordDictB])

I  The  a  bed.  cat  cat.  dog  dog.  face.  hate  love  my  on  sat
0  1    1  1     0    1     1    0     0      1     1     0   1   1    1
1  1    1  1     1    0     0    1     1      0     0     1   1   1    1

In [0]:
def computeTF(wordDict,bow):
  tfDict={}
  bowCount = len(bow)
  for word,count in wordDict.items():
    tfDict[word]=count/float(bowCount)
  return tfDict

In [0]:
tfBowA=computeTF(wordDictA, bowA)
tfBowB=computeTF(wordDictB, bowB)


In [0]:
tfBowA

{'I': 0.1,
 'The': 0.1,
 'a': 0.1,
 'bed.': 0.0,
 'cat': 0.1,
 'cat.': 0.1,
 'dog': 0.0,
 'dog.': 0.0,
 'face.': 0.1,
 'hate': 0.1,
 'love': 0.0,
 'my': 0.1,
 'on': 0.1,
 'sat': 0.1}

In [0]:
tfBowB

{'I': 0.1,
 'The': 0.1,
 'a': 0.1,
 'bed.': 0.1,
 'cat': 0.0,
 'cat.': 0.0,
 'dog': 0.1,
 'dog.': 0.1,
 'face.': 0.0,
 'hate': 0.0,
 'love': 0.1,
 'my': 0.1,
 'on': 0.1,
 'sat': 0.1}

In [0]:
def computeIDF(docList):
  import math
  idfDict = {}
  N = len(docList)
  idfDict= dict.fromkeys(docList[0].keys(), 0)
  for doc in docList:
    for word, val in doc.items():
      if val > 0:
        idfDict[word] += 1
        
  for word, val in idfDict.items():
    idfDict[word] = math.log10(N / float(val))
    
  return idfDict

In [0]:
idfs = computeIDF([wordDictA, wordDictB])

In [0]:
def computeTFIDF(tfBow,idfs):
    tfidf = {}
    for word,val in tfBow.items():
        tfidf[word] = val*idfs[word]
    return tfidf

In [0]:
tfidfBowA = computeTFIDF(tfBowA, idfs)
tfidfBowB = computeTFIDF(tfBowB, idfs)

In [0]:
import pandas as pd
pd.DataFrame([tfidfBowA,tfidfBowB])

I  The    a      bed.       cat  ...      hate      love   my   on  sat
0  0.0  0.0  0.0  0.000000  0.030103  ...  0.030103  0.000000  0.0  0.0  0.0
1  0.0  0.0  0.0  0.030103  0.000000  ...  0.000000  0.030103  0.0  0.0  0.0

[2 rows x 14 columns]

In [0]:
d1

'The cat sat on my face. I hate a cat.'

In [0]:
d2

'The dog sat on my bed. I love a dog.'